-- ============================================================
-- TENANTS — one row per law firm
-- ============================================================
CREATE TABLE tenants (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- USERS — people who log in (lawyers, staff, owners)
-- ============================================================
CREATE TABLE users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID NOT NULL REFERENCES tenants(id),
    email       TEXT NOT NULL,
    full_name   TEXT NOT NULL,
    role          TEXT NOT NULL CHECK (role IN ('owner','lawyer','staff')),
    password_hash TEXT NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, email)
);

-- ============================================================
-- DOCUMENT TYPES — fixed, known list of legal document categories
-- (shared across all tenants — not firm-specific)
-- ============================================================
CREATE TABLE document_types (
    id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type_key  TEXT NOT NULL UNIQUE,   -- 'statement_of_claim', 'subrogation_letter', 'client_receipt'
    label     TEXT NOT NULL           -- 'כתב תביעה', 'מכתב שיבוב', 'קבלה מלקוח'
);

-- ============================================================
-- SENDERS — per-tenant list of known senders.
-- odcanit_prefix is used only at Odcanit submission time, not shown in the UI.
-- ============================================================
CREATE TABLE senders (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenants(id),
    name            TEXT NOT NULL,
    odcanit_prefix  TEXT NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);

-- ============================================================
-- CASES — one extraction job, opened when an intake email arrives.
-- Deliberately thin: this is NOT a case management system.
-- case_number is auto-generated by the backend (first 8 chars of a UUID).
-- ============================================================
CREATE TABLE cases (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id             UUID NOT NULL REFERENCES tenants(id),
    case_number           TEXT NOT NULL,
    status                TEXT NOT NULL DEFAULT 'intake'
                          CHECK (status IN (
                              'intake','extracting','ready_for_review',
                              'in_review','submitted','closed','failed'
                          )),
    created_by            UUID REFERENCES users(id),
    sender_id             UUID REFERENCES senders(id),
    source_email_subject  TEXT,
    odcanit_case_number   TEXT,
    deleted_at            TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, case_number)
);

-- ============================================================
-- DOCUMENTS — one row per uploaded file, linked to a case.
-- file_format and text_extractable are independent facts about the file.
-- ============================================================
CREATE TABLE documents (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id           UUID NOT NULL REFERENCES cases(id),
    tenant_id         UUID NOT NULL REFERENCES tenants(id),
    document_type_id  UUID REFERENCES document_types(id),
    file_name         TEXT NOT NULL,
    storage_path      TEXT NOT NULL,
    file_format       TEXT NOT NULL CHECK (file_format IN ('pdf','docx')),
    text_extractable  BOOLEAN NOT NULL,
    page_count        INT,
    processing_status TEXT NOT NULL DEFAULT 'pending'
                       CHECK (processing_status IN ('pending','extracting','extracted','failed')),
    raw_text          TEXT,
    extraction_raw    JSONB,
    error_message     TEXT,
    deleted_at        TIMESTAMPTZ,
    uploaded_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at      TIMESTAMPTZ
);

-- ============================================================
-- CASE FIELDS — the fixed checklist of data points the system
-- knows how to handle. This is a template; it never references a case.
-- ============================================================
CREATE TABLE case_fields (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    field_key    TEXT NOT NULL UNIQUE,   -- 'client_full_name', 'claim_amount'
    label        TEXT NOT NULL,          -- 'שם הלקוח', 'סכום התביעה'
    data_type    TEXT NOT NULL CHECK (data_type IN ('text','number','date','boolean')),
    is_required  BOOLEAN NOT NULL DEFAULT true,
    sort_order   INT NOT NULL DEFAULT 0
);

-- ============================================================
-- CASE FIELD VALUES — the filled-in answers, one row per case per field.
-- extracted_value is frozen as the AI's original output; value is current/edited.
-- ============================================================
CREATE TABLE case_field_values (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id            UUID NOT NULL REFERENCES cases(id),
    tenant_id          UUID NOT NULL REFERENCES tenants(id),
    field_id           UUID NOT NULL REFERENCES case_fields(id),
    extracted_value    TEXT,
    value              TEXT,
    source_document_id UUID REFERENCES documents(id),
    source_page        INT,
    confidence_score   NUMERIC(4,3),
    status             TEXT NOT NULL DEFAULT 'pending_review'
                       CHECK (status IN ('pending_review','confirmed','edited','rejected')),
    reviewed_by        UUID REFERENCES users(id),
    reviewed_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (case_id, field_id)
);

-- ============================================================
-- ODCANIT SUBMISSIONS — record of every handoff to Odcanit
-- ============================================================
CREATE TABLE odcanit_submissions (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id           UUID NOT NULL REFERENCES cases(id),
    tenant_id         UUID NOT NULL REFERENCES tenants(id),
    payload_sent      JSONB NOT NULL,
    response_received JSONB,
    status            TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','success','failed')),
    error_message     TEXT,
    submitted_by      UUID REFERENCES users(id),
    submitted_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- AUDIT LOG — who did what, when
-- ============================================================
CREATE TABLE audit_log (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID NOT NULL REFERENCES tenants(id),
    user_id     UUID REFERENCES users(id),
    case_id     UUID REFERENCES cases(id),
    action      TEXT NOT NULL,
    details     JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_senders_tenant_id ON senders(tenant_id);
CREATE INDEX idx_documents_case_id ON documents(case_id);
CREATE INDEX idx_cases_tenant_id ON cases(tenant_id);
CREATE INDEX idx_documents_tenant_id ON documents(tenant_id);
CREATE INDEX idx_case_field_values_case_id ON case_field_values(case_id);
CREATE INDEX idx_case_field_values_tenant_id ON case_field_values(tenant_id);
CREATE INDEX idx_odcanit_submissions_case_id ON odcanit_submissions(case_id);
CREATE INDEX idx_audit_log_case_id ON audit_log(case_id);

-- ============================================================
-- ROW-LEVEL SECURITY — tenant isolation enforcement
-- FastAPI must run: SET LOCAL app.current_tenant_id = '<uuid>'
-- at the start of each request transaction, right after auth.
-- ============================================================
ALTER TABLE senders ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_field_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE odcanit_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON senders
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
CREATE POLICY tenant_isolation ON cases
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
CREATE POLICY tenant_isolation ON documents
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
CREATE POLICY tenant_isolation ON case_field_values
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
CREATE POLICY tenant_isolation ON odcanit_submissions
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
CREATE POLICY tenant_isolation ON audit_log
    USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

-- Note: 'users' deliberately has no RLS policy — login must look up
-- a user by email before any tenant context exists.
