"""add cases and case_fields tables, update documents

Revision ID: 3cab424d39e3
Revises: a64ac1c39861
Create Date: 2026-05-01 20:53:29.226759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cab424d39e3'
down_revision: Union[str, Sequence[str], None] = 'a64ac1c39861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('office_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_type', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('otkanit_case_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_fields',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_values', sa.Text(), nullable=True),
    sa.Column('was_corrected', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'documents', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'case_id')
    op.drop_table('case_fields')
    op.drop_table('cases')
    # ### end Alembic commands ###
